### ISSUE TITLE
DBどうするか

### ISSUE THREAD

**Issue by minmin0530** [we-are-what-we-do/we-are-what-we-do#1]
候補：AWS
ReactもDBと同じwebサーバーにあげたほうがよさそう
→shonさんが試した感じで、決定（学内のAWSで試せる）
→AWSでいけそうなら、tsumicharaのほうでアカウント作成

**Comment by teraoa** [comment]
（awsを使用するなら）
GitHubをミラーリングして、mainブランチに変更がある度にAWSのCodeCommitやCodePipelineが走るようにして、
Reactの成果物をs3バケット内に自動で配置するような仕組みをいずれ実現したいですね。

**Comment by minmin0530** [comment]
teraoさんがCLIをshonさんに渡す

**Comment by CA01971172** [comment]
RaikaさんにPostgresとPostGISを使用してDBサーバーを構築してもらうことになりました。

**Comment by CA01971172** [comment]
DBサーバーやAPサーバーをdocker-composeで構築し、EC2に乗せる感じで
インスタンスタイプは要検討
RaikaさんがdockerをEC2に乗せる
