### ISSUE TITLE
React と DBのIF（フロー図右側ピンク枠）

### ISSUE THREAD

**Issue by minmin0530** [we-are-what-we-do/we-are-what-we-do#10]

**Comment by CA01971172** [comment]
AWS DynamoDBとReactを接続する
(難しそうなら別のサービスに変更する可能性がある)

トランザクションの面からRDBを使用するかも？(その場合APIサーバー用Docker内のVolumeでMariaDB等を動かすのか、AWS RDBを使用するのか等は未定)

また、バックエンドとの接続用の関数をimportするのか、必要な関数や取得したデータをまとめてProviderに梱包してuseContextするのかも未定

**Comment by CA01971172** [comment]
- `DBサーバー(AWS RDS?) <-> APサーバー(ECS) <-> Webサーバー(S3)`といった感じでDBとReactを接続する
- Fetch APIでDBサーバーとGET/POST通信を行うような関数や、APサーバーから取得したリングデータをuseStateで管理しているものを、Providerに梱包し、必要なコンポーネントでuseContextする

**Comment by CA01971172** [comment]
## APIを呼び出す関数の作成
/src/api/fetchDb.ts
APIを呼び出す関数を作成しました。
- getLocationConfig(): Promise<Points>
    ピンの全設定データを取得する関数です。
    引数はありません。
    戻り値は、各idフィールドにGeoJSONのPoint型の値が割り当てられたオブジェクトを返します。
- getRingData(location: string): Promise<RingsData>
    ピン一か所を指定して、指定箇所に対応するリングのデータを取得する関数です。
    引数には、ピンを指定する場所の名前(id)を渡します。
    戻り値は、各idフィールドにRingDataという型の値が割り当てられたオブジェクトを返します。
- postRingData(data: RingData): Promise<Response>
    リングのデータを1つ、APサーバーに送信する関数です。
    引数には、RingDataという型でリングのデータを渡します。
    戻り値は、Response型のレスポンスを返します。
- postNftImage(base64Data: string): Promise<Response>
    撮影した画像をAPサーバーに送信する関数です。
    引数には、base64バイナリ文字列を渡します。
    戻り値は、Response側のレスポンスを返します。

## Providerの作成
/src/providers/DbProvider.tsx
リングのデータを管理するためのProviderを作成しました。
- ringData
    useStateで管理されたRingData型のデータです。
- initializeRingData(location: string): Promise<void>
    リングのデータを取得して、ringDataに入力する関数です。
    引数には、ピンを指定する場所の名前(id)を渡します。
    戻り値はありません。(実際には戻り値のないPromiseオブジェクトを返します)
