### ISSUE TITLE
システム設計　概要図

### ISSUE THREAD

**Issue by minmin0530** [we-are-what-we-do/we-are-what-we-do#2]
Blender　→　Three.js
Unity　→　AR.js
に置き換えてください

https://cdn.discordapp.com/attachments/1131149198314709032/1146674656485572690/Program_Flow_v0.1_2.png

https://cdn.discordapp.com/attachments/1131149198314709032/1146674656737251358/Program_Flow_v0.1.png

**Comment by minmin0530** [comment]
更新版

https://cdn.discordapp.com/attachments/1131149198314709032/1148669468789190798/Program_Flow_v0.2.png

https://cdn.discordapp.com/attachments/1131149198314709032/1148669468420079666/Program_Flow_v0.2_2.png

**Comment by teraoa** [comment]
https://cdn.discordapp.com/attachments/1131149031989575690/1158771273699184640/WebApplication_v0.2.png

https://cdn.discordapp.com/attachments/1131149031989575690/1158771323552677919/LivePage_v0.2.png
