### ISSUE TITLE
各種通信とIF（インターフェース）

### ISSUE THREAD

**Issue by minmin0530** [we-are-what-we-do/we-are-what-we-do#22]

**Comment by teraoa** [comment]
shon's project detail 
https://github.com/orgs/we-are-what-we-do/projects/3

**Comment by CA01971172** [comment]
メインページとライブページにおける、
サーバーからデータを取得する処理が完成しました。

以下を行い次第、本issueをcloseします。
- 本番環境に合わせたエンドポイントの修正
- リングデータの取得/送信テスト
- Base64画像データの送信テスト
