### ISSUE TITLE
ロケーションマーカーでのAR表示

### ISSUE THREAD

**Issue by minmin0530** [we-are-what-we-do/we-are-what-we-do#23]

**Comment by teraoa** [comment]
**AR.js は、typescript で使えない（型定義できない）**

1. javascriptで作成したものを無理やり型定義してtypescriptで読む
2. 他に開発してる人のライブラリを借りる
3. any で定義する

　→ 9/20　「他に開発してる人のライブラリを借りる」を選択

**オプション**

1. AR.js + typescript   LocationBased　tsとの互換性なし、技術的に難
　→ 9/22　A-Frameを使えるようにJSXを拡張することを試す

2. MindAR + typescript   LocationBased　tsとの互換性あり、動作不安定　バグがあり使えない
3. MindAR + typescript     ImageTracking　tsとの互換性あり、安定　

5. AR.js + typescript   MarkerBased　tsとの互換性ないが、動作確認済み
6. AR.js + typescript  ImageTracking　？ -> 不可能

**Comment by teraoa** [comment]
結論：AR.jsは使用せず、Three.jsの背景にカメラ画像を使用する案で進める
