### ISSUE TITLE
初期処理　カメラ

### ISSUE THREAD

**Issue by minmin0530** [we-are-what-we-do/we-are-what-we-do#24]
- カメラ
- GPS
- IP Address

**Comment by teraoa** [comment]
カメラ
　QR読み込む時点で許可しているはずだから、WEB側での許可は不要

GPS
　現在地の緯度経度を取得　-> 済
　ピン設定GPS（GeoJSONを取り込み）　-> 済
　現在地とピン設定の範囲判定　-> 　範囲内外の判定フラグを戻り値に実装済　9/26

IPアドレス
　現在のIPアドレスを取得　-> 済
　前回のIPアドレスを取り込み　-> in Progress
　現在と前回のIPアドレス判定
