### ISSUE TITLE
中継ページ作成

### ISSUE THREAD

**Issue by teraoa** [we-are-what-we-do/we-are-what-we-do#40]

**Comment by CA01971172** [comment]
サーバーとの通信処理の実装が完了しました。
- リングの初期表示
- リングの定期更新

あとは、以下の実装が残っています。
- エンドポイント名の修正(本番環境に合わせたものに)
- 緯度・経度の表示等、必要があれば削除

**Comment by teraoa** [comment]
10/18(水) 13:30 - に愛媛大学の大型ビジョンに投影確認します
