### ISSUE TITLE
県歴史文化博物館で初期化ボタン無効

### ISSUE THREAD

**Issue by teraoa** [we-are-what-we-do/we-are-what-we-do#72]
10/29 @shuno-on 
現在、県歴史文化博物館に来ていますが、アンドロイドもアイフォンも、半径内にいるはずなのに、ともに撮影ボタンとARリングの初期化ボタンが無効状態です。これはバグチェックの修正途上での折込済のやつでしょうか？

**Comment by teraoa** [comment]
10/30 @CA01971172 
すみません、コードを確認したところ、ピン設定データはS3の/test/test_pin.jsonを参照していました。
https://wawwd.net/test/test_pin.json

こちらを変更お願いします。
https://ap-southeast-2.console.aws.amazon.com/s3/object/we-are-what-we-do?region=ap-northeast-1&prefix=test/test_pin.json

**Comment by teraoa** [comment]
@shuno-on 
設定データの緯度経度は「県歴史文化博物館」を指していたようですので、現地でのGPSがずれておかしかったのか？！
<img width="958" alt="スクリーンショット 2023-10-30 12 13 51" src="https://github.com/we-are-what-we-do/we-are-what-we-do/assets/39430191/7a0b1c6c-d390-4ffe-b9f1-69977f7f7d23">

**Comment by teraoa** [comment]
県歴史文化博物館設定情報
https://we-are-what-we-do.s3.ap-northeast-1.amazonaws.com/test/test_pin.json

```
{
      "geometry": {
        "coordinates": [
          33.3641000,
          132.518310
        ],
        "type": "Point"
      },
      "id": "1bbf8bb5-4a1f-2c3a-9657-9b261e617cf4",
      "properties": {
        "localize": {
          "jp": "愛媛県歴史文化博物館"
        },
        "radius": 100
      },
      "type": "Feature"
    },
```

**Comment by shuno-on** [comment]
![a_歴博_屋外_クローム](https://github.com/we-are-what-we-do/we-are-what-we-do/assets/148728000/836f641d-a956-47b2-848b-242e4fc43f97)
![a_歴博_屋内_クローム](https://github.com/we-are-what-we-do/we-are-what-we-do/assets/148728000/07d5a643-da05-4655-8b4a-a244496b95d3)
![i_歴博_クローム](https://github.com/we-are-what-we-do/we-are-what-we-do/assets/148728000/819083da-65ba-41b8-87c2-37d4ec75ee0f)
![i_歴博_屋外_エッジ](https://github.com/we-are-what-we-do/we-are-what-we-do/assets/148728000/d59d8dbd-1cce-4814-8af2-5b8c59ec6ab5)
![i_歴博_屋内_エッジ](https://github.com/we-are-what-we-do/we-are-what-we-do/assets/148728000/4cee2258-4e52-4d5e-acb8-a62a0d21262d)

30分くらいした後から、同じ場所でもできるようになりました。ただし、歴博に限りませんが、iphoneのクロームがずっと撮影・初期化ボタンが無効なのは、直っていませんm（＿　＿）m
