### ISSUE TITLE
範囲外でのメッセージ表示

### ISSUE THREAD

**Issue by teraoa** [we-are-what-we-do/we-are-what-we-do#73]
初期表示で、ピンまでの距離がすべて（ピンの数だけ）表示されると、メッセージボックスが多すぎて閉じるのがやや面倒

**Comment by CA01971172** [comment]
console.logで対応するのが良いのですが、
スマホだと開発者モードが開けないので暫定的にこのような対応となっています。
テスト用のメッセージボックスであり、本番では表示されないのでご了承ください。
