### ISSUE TITLE
衝突メッセージが連続してしまう

### ISSUE THREAD

**Issue by shuno-on** [we-are-what-we-do/we-are-what-we-do#74]
アイフォン、初の衝突メッセージ！なんかちょっとうれしい、と思ったら、以降、生成しようとするリングの位置がランダムに変わっていっているのに、ずっと衝突メッセージが出続けます。
アイフォン自体は再起動しても同様の症状、収まらず。
アイフォンで撮影できないから、アンドロイドが連続撮影になるため、アンドロイドは分からず、です。
![衝突１](https://github.com/we-are-what-we-do/we-are-what-we-do/assets/148728000/ed9b5212-a4de-47b9-ada0-6dfff47fe590)
![衝突2](https://github.com/we-are-what-we-do/we-are-what-we-do/assets/148728000/cafaed72-c1a1-47b9-aa2a-50c757330ef3)
![衝突3](https://github.com/we-are-what-we-do/we-are-what-we-do/assets/148728000/a31c09a8-d54c-4709-8ea9-c47fb29c5500)

**Comment by shuno-on** [comment]
昨日は連続撮影扱いになって写真が取れなかったアンドロイドですが、本日は撮れた、と思ったら、なんとこちらでも衝突メッセージ！＠愛媛新聞社
![Uploading A-衝突４.jpg…]()

**Comment by CA01971172** [comment]
衝突メッセージは現状、サーバーにリングデータを送信できなかった場合、どのような場合でも(普通にサーバーにアクセスできなかった場合等)表示されてしまいます

メインページは現在仮データベースを使用しているため、データが衝突した際に送信を弾く処理は実装されていません

つまり、仮データベースとの接続エラーである可能性が高そうです
同様の現象をこちらでも確認いたしました。

**Comment by shuno-on** [comment]
うちの社員が四国中央の大王製紙とデジタルウェイブで試した時も、同様だったとの報告きました。アイフォンです

**Comment by CA01971172** [comment]
すみません、メインページでのリングデータ送信先は本番サーバーになっていたようです。

現在、メインページ(`https://wawwd.net/`)からサーバー(`htpps://api.wawwd.net/`)にリングデータを送信できない問題が発生しており、それが影響しているものと思われます

**Comment by teraoa** [comment]
本番用は解決されている
衝突のテスト　@teraoa と　@shuno-on  をしてエラー再現しなければクローズ

**Comment by teraoa** [comment]
本番用は解決されていません！
https://discord.com/channels/1131147232356343869/1132428691377504266/1170584665002885130

**Comment by teraoa** [comment]
Highに変更しました

**Comment by teraoa** [comment]
プログラム変更等により、状況が再現されないので、一旦クローズ
