### ISSUE TITLE
インスタンス変更対応

### ISSUE THREAD

**Issue by teraoa** [we-are-what-we-do/we-are-what-we-do#77]
**現状**
フロントエンド仕様A
バックエンド仕様B

【仕様A】
あくまでマスターはひとつでそのマスターDEIに対して、複数地点からリングを増やす
それぞれの場所で、それぞれのDEIをつくるわけではない

【仕様B】
インスタンスはロケーションに依存する
別ロケーションからのリング生成は新しくインスタンスを生成する

**問題**
例えば、以下のような状況で、
ロケーションAからリングを送信しようとすると、
ロケーションAから接続した全ユーザーは、インスタンスA-2にindex: 69のデータしか送信できず、二人目以降は常にコンフリクトを起こします

これは、フロントエンドは開始時間が最新のインスタンス(この例で言うとインスタンスB-1)を取得するためです
そのため、インスタンスB-1の最後の空きindexであるindex: 69でリングデータを送信しようとするのですが、
受信元はインスタンスB-1でも、送信先はインスタンスA-2のため、このような問題が発生します

インスタンスA-1
ロケーション: ロケーションA
開始時間: 11/3生成
リング数: 70/70

インスタンスA-2
ロケーション: ロケーションA
開始時間: 11/4生成
リング数: 0/70

インスタンスB-1
ロケーション: ロケーションB
開始時間: 11/5生成
リング数: 69/70 (空きindex: 69)

**Comment by teraoa** [comment]
**結論**
仕様A　あくまでマスタのDEIはひとつで、どのロケーションからも同じDEIをつくる
バックエンド -> 11/3中に対応予定

**影響**
11/3大洲で撮影されたリングデータとインスタンスデータは本番DBに残らない
画像データはバックアップ可

**Comment by HalsekiRaika** [comment]
対応が完了しました
