### ISSUE TITLE
カメラボタンが半透明で押せない状態

### ISSUE THREAD

**Issue by teraoa** [we-are-what-we-do/we-are-what-we-do#79]
アイフォン・サファリはカメラボタンが半透明で押せない状態

**Comment by teraoa** [comment]
@HalsekiRaika 
Safariはブラウザの仕様上難しいかもしれないですね
対応ブラウザの掲載をした方が良かったかもしれないです

**Comment by teraoa** [comment]
#70 と同じ現象？

**Comment by shuno-on** [comment]
私のｉｐｈｏｎｅのサファリは問題なし。ただ、大洲の参加者でｉ－サファリで半透明、複数人あり。#70 と同じ現象ならｉｐｈｏｎｅの参加者の中には、サファリもクロームもダメという人が出る可能性も？

**Comment by teraoa** [comment]
https://github.com/we-are-what-we-do/we-are-what-we-do/issues/70 と同じ現象のためクローズ
