### ISSUE TITLE
赤警告で衝突メッセージ

### ISSUE THREAD

**Issue by teraoa** [we-are-what-we-do/we-are-what-we-do#80]
アンドロイド・クローム、赤警告で衝突メッセージ。リング５つ目くらいで、大洲のみで、本当に衝突しているとは考えられない

**Comment by teraoa** [comment]
@CA01971172 
衝突メッセージなのですが、
現状、サーバーとの通信エラーはすべて衝突メッセージになります

**Comment by shuno-on** [comment]
大洲の最後にtsumicharaのｉｐａｄで「はい（登録）」をした時にも出た。タブレットの検証例はいまだ少なし

**Comment by teraoa** [comment]
Andoroidは、シークレットモードにしないと、必ず衝突メッセージがでます

**Comment by teraoa** [comment]
<img width="1129" alt="スクリーンショット 2023-11-05 15 35 11" src="https://github.com/we-are-what-we-do/we-are-what-we-do/assets/39430191/7edd768b-04bc-45d4-80d9-2ec15810f1f0">

**Comment by teraoa** [comment]
https://wawwd.net/testProduct/ & シークレットモードは同様
https://wawwd.net/testDevelopment/ ＆シークレットモードは再現しない

**Comment by teraoa** [comment]
@CA01971172 
サーバーデータをリセットしたことで、ロケーションIDが変更されたことが影響している可能性はありますね
localStorage内のロケーションデータを参照してしまって、送信するリングデータのロケーションIDが古いままになっている

**Comment by teraoa** [comment]
発生条件は、既にロケーションデータを読み込んでいるユーザーのみ（ = 新規ユーザーは発生しない）
 eTag実装（~11/11）で解消予定

**Comment by CA01971172** [comment]
[こちら](https://github.com/we-are-what-we-do/we-are-what-we-do/issues/80#issuecomment-1793652464 )のログですが、
`{url: 'https://testapi.wawwd.net/rings', data: {...}}`の、`data: {...}`の部分に送信するリングデータが記載されています。
そのため、今後同様の事例が発生した際は、可能であればリングデータも合わせて添付していただければ原因究明が捗ります。

**Comment by teraoa** [comment]
シークレットモードでは衝突メッセージ再現されませんでした。通常モードでのログを添付します
<img width="1159" alt="スクリーンショット 2023-11-06 16 29 42" src="https://github.com/we-are-what-we-do/we-are-what-we-do/assets/39430191/8f112927-6c69-4025-a8b2-e7b46102a4c9">

**Comment by teraoa** [comment]
エラー解消済み
